### ISSUE TITLE
Autographa MT API issues

### ISSUE THREAD

**Issue by bijob89** [Bridgeconn/vachan-api#45] opened 2020-02-15 15:38 UTC
Below is the list of issues that needs to be looked at:

1. The senses received from the response of `v1/translations/<sourceId>/<targetId>/<token>` (`GET` method), is an array of characters instead of words. For ex `{"translation": "", "senses": ["o", "w", "n", "n", "e", "w", "s", "o", "m", "e"]}`.
2. Download draft api is not working. Response received `{"success": false, "message": "Server error"}`. The body content `{projectId: 66, bookList: ["jhn"]}`

**Comment by kavitharaju** [comment] 2020-02-17 04:36
We are looking into the causes behind these issues.
The download draft issue is only occuring for the project wity id 66.
As we are woking on fixing it, you can work with another project_id that doesnot throw the above error. 
Project_id 69 seems to be working fine.

**Comment by kavitharaju** [comment] 2020-02-17 05:35
The first issue of getting ["o", "w", "n", "n", "e", "w", "s", "o", "m", "e"] for senses occur when the token updation is done incorrectly.
The API `/v1/autographamt/projects/translations` is expected to take the input as follows
```
	data = {'token':tokenword,
			'translation':trans,
			'projectId': projectid, 
			'senses':["owning"]
			}
```
I observed that when the senses is passed as a string instead of list of string we get the above mentioned issue. Can you check if the UI passes it as list and not plain string?

**Comment by kavitharaju** [comment] 2020-02-17 08:59
The issue relating to the download draft has also been fixed now.

**Comment by bijob89** [comment] 2020-02-17 18:52
Thanks @kavitharaju . They are fixed.

**Comment by joelthe1** [comment] 2020-02-17 19:19
> The first issue of getting ["o", "w", "n", "n", "e", "w", "s", "o", "m", "e"] for senses occur when the token updation is done incorrectly.
> The API `/v1/autographamt/projects/translations` is expected to take the input as follows
> 
> ```
> 	data = {'token':tokenword,
> 			'translation':trans,
> 			'projectId': projectid, 
> 			'senses':["owning"]
> 			}
> ```
> 
> I observed that when the senses is passed as a string instead of list of string we get the above mentioned issue. Can you check if the UI passes it as list and not plain string?

@kavitharaju If you haven't already could you add a check in the API to ensure if the passed in senses argument to the API is a `list` and not a `str` object?

**Closed** 2020-09-14 04:13 UTC
