### ISSUE TITLE
User getting 403 error for suggestion API & sentence API

### ISSUE THREAD

**Issue by ashish-garg-25** [Bridgeconn/vachan-api#396] opened 2022-07-07 21:11 UTC
User is added to the respective project but still getting 403 error while hitting sentence and suggestion API

**Comment by kavitharaju** [comment] 2022-07-08 10:48
@ashish-garg-25 Could you please tell me the error message you get from API server?

Also couple of things to make sure you are accessing API the right way, 
- is the user a AGUser? Someone who was registered via the APP and not directly via API call or swagger?
- are you passing the API with `app: Autographa` in header?

**Comment by kavitharaju** [comment] 2022-07-13 07:51
Are you still facing this issue?

**Comment by kavitharaju** [comment] 2022-07-20 12:03
Closing this issue assuming the above suggestions helped and the issue is no more.

**Closed as completed by kavitharaju** 2022-07-20 12:03 UTC
Labels: translation module, Auth
